### ISSUE TITLE
add eslint to project?

### ISSUE THREAD

**Issue by fatters** [EoinDavey/Setanta#1]
Hi there, quality project and brilliant name!

Saw your last commit on adding the strict comparison operator and was just wondering if you see any benefit in adding eslint to audit the ts files in the `src` directory (tests and all)?

Locally, I just set up a barebones eslint config and ran it against the `src` directory and, to be fair, it is just tests affected.

This is for `builtins.test.ts`
<img width="763" alt="Screen Shot 2019-12-20 at 09 47 04" src="https://user-images.githubusercontent.com/4260220/71245961-b9faf480-230d-11ea-9bd9-f40149cae999.png">

Anyways, just a suggestion! Feel free to close this if you don't think it'd be relevant :) 

If you would like to add linting, I'd be happy to open a PR with my additions (would you prefer I fix the linting issues too or would you prefer to do that?)

Cheers!

**Comment by EoinDavey** [comment]
Hey, 
Thanks for your interest in the project. 
Yeah adding some linting is definitely on my todo list, have just been putting it off.
Unfortunately as this is my final year project I can't accept outside pull requests for the time being.
Once the thesis is written up and the university side of it is finished, I'll be very happy to take any outside contributions.
The project is still a very much WIP, but I'm planning on adding some basic info to the README soon on syntax/semantics.
You might have noticed by now but if you want to play around with the language you can build the npm package locally and run the node_build/cli.js file, or you can try it in browser here: https://vey.ie/goto?go=fyp. This browser version lags behind the local REPL by a few commits though usually.

Thanks again,
Eoin

**Comment by fatters** [comment]
> or you can try it in browser here: https://vey.ie/goto?go=fyp.

Oh cool! Thanks for that. And yep, fair do's that makes sense. Best of luck with your final year!! I will close this issue now.
